# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
scss:
  scss_dir: _scss
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "/n/n"
incremental         : true

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
url                 : "https://jhfreedman.com" # the base hostname & protocol for your site
baseurl             : "" # the subpath of your site, e.g. /blog


# Outputting
timezone            : America/New_York

verbose             : false

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false



  cache_dir: /home/jhfreedman/.jekyll-cache
